### ISSUE TITLE
widget.fs requires glib > 2.53

### ISSUE THREAD

**Issue by wimstefan** [lcpz/lain#387] opened 2018-02-18 08:22 UTC
``` sh
awesome v4.2-260-gb2d1e857-dirty (Human after all)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.0
````

`Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio`

I've updated lain to @63c9c76 and since then the fs widget stopped working with the above error. I tried to adapt my rc.lua to the new requirements in calling the widget as below:
``` lua
local widget_fs = lain.widget.fs({                    
  notification_preset = { font = beautiful.mono_font },
  settings = function()                                            
    widget:set_markup(markup.font(beautiful.icon_font, "") .. markup.font(beautiful.font, "  " .. fs_now["/"].used .. " " .. fs_now["/"].units))
  end                                                                 
})
```

Please let me know if you need more information ...

**Comment by lcpz** [comment] 2018-02-18 11:32
1. Try updating LGI to version latest version (0.9.2).

2. Check if you have Gio/Glib version >= 2.5.

For the second point, [this](https://lazka.github.io/pgi-docs/Gio-2.0/index.html) is the latest version for Debian, it should be the same for Ubuntu.

**Comment by wimstefan** [comment] 2018-02-18 13:19
Thank your for your swift response!

Upgrading LGI (and hence Lua) isn't that easy since I'm sitting on a Gentoo system and there are still too much packages depending on the default Lua version on Gentoo :-/

So if the error occurs because of too old software versions I'll have to live without any fs info in my bar ...

**Comment by lcpz** [comment] 2018-02-18 13:31
LGI works with all 5.x Lua versions, there shouldn't be dependencies.

It is also possible to have more Lua versions at once (like Python).

I suggest you try my points above.

**Comment by lcpz** [comment] 2018-02-21 19:31
> I suggest you try my points above.

Just FYI, it'd be of benefit for me too if you try, so that I can be really sure if it's a version compatibility, or some other issue on your side.

**Comment by wimstefan** [comment] 2018-02-23 23:04
I'm terribly sorry if I offended you by not responding! But as I said it's not that easy to install other LGI versions on a Gentoo system ... I didn't succeed until now hence I couldn't report back anything :-/

I've asked for some help on the Gentoo #irc channels but didn't get any response yet - next step (if I've recovered from my illness) will be to open a bug report on the Gentoo bug system ... I hope I can get enough help to finally follow your suggestions.

**Comment by lcpz** [comment] 2018-02-24 12:02
No offence taken, don't worry! I didn't want to give you this impression, sorry.

As far as I can see, Gentoo's current upstream versions of LGI and Gio/Glib are old, so it's not a bug, only a pending update and therefore they might just reply you to respect their times.

Just install LGI and Gio/GLib by yourself, it's very easy:

1. **Gio/GLib**: 
    ```shell
    wget https://download.gnome.org/sources/glib/2.54/glib-2.54.3.tar.xz
    tar xf glib-2.54.3.tar.gz
    cd glib-2.54.3
    ./configure
    make
    # from now on, become root if necessary
    rm -rf /install-prefix/include/glib.h /install-prefix/include/gmodule.h
    make install
    ```
2. **LGI**: install [luarocks](https://packages.gentoo.org/packages/dev-lua/luarocks) then execute `luarocks install lgi`

Easy as cake, but let me know if you need further help.

**Comment by wimstefan** [comment] 2018-02-24 16:12
Good to hear!
I was able to update at least LGI to 0.9.2 "the Gentoo way" but trying the same with glib-2.54.3 is a whole different story :-/ I get a lot of dependency errors and emerge simply refuses to execute the update. That scares me away from updating manually as you suggested ...

Status now with LGI 0.9.2 is:
``` lua
awesome v4.2-260-gb2d1e857-dirty (Human after all)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```
throws this error first:
``` lua
error while running function!
stack traceback:
	/home/swimmer/.config/awesome/lain/widget/fs.lua:73: in function 'func'
	/usr/share/awesome/lib/gears/object.lua:123: in function 'emit_signal'
	/home/swimmer/.config/awesome/lain/helpers.lua:100: in function 'newtimer'
	/home/swimmer/.config/awesome/lain/widget/fs.lua:125: in function 'fs'
	/home/swimmer/.config/awesome/rc.lua:356: in main chunk
error: /home/swimmer/.config/awesome/lain/widget/fs.lua:73: attempt to call field 'unix_mounts_get' (a nil value)
```
followed by an awesome lot of the following lines:
``` lua
2018-02-24 14:54:04 E: awesome: Error during a protected call: /home/swimmer/.config/awesome/lain/util/markup.lua:28: attempt to concatenate local 'font' (a nil value)
stack traceback:
	/home/swimmer/.config/awesome/lain/util/markup.lua:28: in function 'font'
	/home/swimmer/.config/awesome/rc.lua:336: in function 'settings'
	/home/swimmer/.config/awesome/lain/widget/cpu.lua:70: in function 'func'
	/usr/share/awesome/lib/gears/object.lua:123: in function </usr/share/awesome/lib/gears/object.lua:120>
	(tail call): ?
	[C]: in function 'xpcall'
	/usr/share/awesome/lib/gears/protected_call.lua:30: in function </usr/share/awesome/lib/gears/protected_call.lua:28>
	(tail call): ?
	/usr/share/awesome/lib/gears/timer.lua:92: in function </usr/share/awesome/lib/gears/timer.lua:91>
```

**Comment by lcpz** [comment] 2018-02-24 16:44
Thank you, this proves that it is not an LGI version issue, since the error persists.

Let us check if it is a Gio thing. Don't be scared to install manually GLib as reported above: if you have any issue, you can just do `make uninstall` and `emerge` again the Gentoo version.

About the new error, within your `settings` function in the cpu widget, you are calling `lain.util.markup.font` with a nil argument as the font. [This](https://github.com/lcpz/lain/blob/master/util/markup.lua#L27) is the correct argument list.

**Comment by wimstefan** [comment] 2018-02-24 17:36
I did a manual install as you recommended but I still get the same error even with glib 2.54.3 installed in /usr/local and the system version glib 2.52.3 uninstalled.

Regarding the font error I only get it if I enable the `widget_fs` code as show above. That doesn't make sense to me ?!?

**Comment by lcpz** [comment] 2018-02-25 10:51
OK, so it's not a dependencies version issue, but something subtle probably related to some `Gio` call.

Please link me your configurations.

**Comment by wimstefan** [comment] 2018-02-25 11:07
You can find it [here](https://gist.github.com/wimstefan/e8ee756d472a9c466feec2eea37ab99d)

**Comment by lcpz** [comment] 2018-02-26 11:33
I [adapted](https://gist.github.com/anonymous/889ccd8e81416c840bf24e8a6e96c946) and tried your `rc`, but I can't reproduce any issue.

Can you try multicolor config from my [themes](https://github.com/lcpz/awesome-copycats) and check if the error still persists?

**Comment by wimstefan** [comment] 2018-02-26 14:44
Oh wow! Thank you so much for all the time you're investigating into that!

I've followed your advice and used your multicolor theme from awesome-copycats.git (which I've already cloned but I re-did that to exclude any error) using those steps:
``` sh
git clone --recursive https://github.com/lcpz/awesome-copycats.git ~/tmp/awesome/awesome-copycats.git
rm -f ~/.config/awesome/
ln -sf ~/tmp/awesome/awesome-copycats.git ~/.config/awesome
cd ~/.config/awesome
cp rc.lua.template rc.lua
```
The default template points already to the multicolor theme so I should be all set. Restarting X did not succeed though to my big embarrassment :-/
The error showing up is [here](https://gist.github.com/anonymous/3d37c96c4602de7a962287b367b98736)

Sorry for the inconvenience :-(

**Comment by lcpz** [comment] 2018-02-26 15:33
The original error is still there, so it's system related.

I don't understand: if you have Gio/GLib/LGI up to date, then how is possible that you don't have `Gio.unix_mounts_get()`?

@psychon I'm sorry to bother you, but since you helped on #272, perhaps you have any clue about this?

**Comment by lcpz** [comment] 2018-02-26 15:39
Quoting [here](https://developer.gnome.org/gio/stable/gio-Unix-Mounts.html#gio-Unix-Mounts.description):

> Note that &lt;gio/gunixmounts.h> belongs to the UNIX-specific GIO interfaces, thus you have to use the gio-unix-2.0.pc pkg-config file when using it.

@wimstefan Probably the Gentoo version doesn't have this config/flag enabled, and probably even the standard configuration in manual install too. This could be the cause.

**Comment by psychon** [comment] 2018-02-26 16:13
So.. according to https://packages.gentoo.org/packages/dev-libs/glib, glib is at least 2.50.3-r1 in Gentoo (and gio is part of glib according to http://www.portagefilelist.de/site/query/listPackageFiles/?category=dev-libs&package=glib&version=2.46.2-r2&do#result).

According to https://developer.gnome.org/gio/2.50/gio-Unix-Mounts.html#g-unix-mounts-get, this function is marked as `[skip]` in Gio 2.50. Same is true for Gio 2.52. Only 2.54 replaces `[skip]` with an actual useful annotation, so that's the minimum required version.

So @lcpz how about `if not require("lgi").Gio.unix_mounts_get then error("This module requires at least Gio 2.54 while your version seems to be older (Gio.unix_mounts_get() not found)") end`?

Now... so if I understood correctly, @wimstefan installed a newer Gio version manually. To what prefix / where? LGI uses a file like `/usr/lib64/girepository-1.0/Gio-2.0.typelib` that contains information about the available functions. The hand-built GLib should have installed such a file somewhere (I guess, or is generating these files turned off if some needed dependency is missing? I don't know, but I guess on Gentoo everything needed is installed?). I would guess something like `/usr/local/lib/girepository-1.0`.

Anyway, find that file. I will assume it is `/usr/local/lib/girepository-1.0/Gio-2.0.typelib`. In this case you need `GI_TYPELIB_PATH=/usr/local/lib/girepository-1.0` for LGI to find and use this file. Testing can be as easy as `GI_TYPELIB_PATH=/usr/local/lib/girepository-1.0 lua -e 'require("lgi").Gio.unix_mounts_get()` (this should produce an error currently / without the env var, but should start working with the env var).

If this works, the remaining problem is "how to start awesome with this env var?". This depends on how you start awesome. Do you use a display manager (slim, gdm, ...) and just select awesome there? Uhm. I guess this then requires messing with `/usr/share/xsessions/awesome.deskop`. The easiest approach could be to create a shell script containing
```
#!/bin/sh
GI_TYPELIB_PATH=foo exec awesome
```
and use that instead of `awesome` in the desktop file.

**Comment by wimstefan** [comment] 2018-02-26 22:17
Wow that is quite an extended and deep answer. Thank you so much @psychon for that!

In the meantime I've uninstalled the manual glib-2.54.3 again and disabled the fs.lua widget for the time being. If I've more time again I'll re-install glib-2.54.3 manually and will test it with GI_TYPELIB_PATH to see if that works. In that case it's very easy to start awesome with this env var since I'm using good old startx ... ;-)

**Comment by lcpz** [comment] 2018-02-27 12:09
I'm going to update the wiki and `fs` itself with a check. Also, I'll keep this open for the time being, so that it is more visible.

**Comment by ndarwincorn** [comment] 2018-04-13 00:57
@lcpz - I'm seeing this issue as reported by folks in lcpz/awesome-copycats#198 and lcpz/awesome-copycats#226 (the `at_screen_connect...nil` error) on a fresh Arch install, with LGI @ 0.9.2 and GLib @ 2.56.1.

Disabling the fs module usage in the theme resolves it. Lemme know if you want further troubleshooting/whatever.

**Comment by lcpz** [comment] 2018-04-13 11:32
@ndarwincorn I'm on Arch and don't have the issue, so you're clearly missing something.

Please do everything is reported [here](https://github.com/lcpz/lain/blob/master/ISSUE_TEMPLATE.md).

**Comment by ndarwincorn** [comment] 2018-04-18 23:47
@lcpz - I can't repro this so it's no worries.

**Comment by trumbis** [comment] 2018-05-18 07:48
I am on Parrot OS (a Debian derivative).
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

I can hopefully edit this with my x.org error, but the exact same error of "at_screen_connect" is problematic.
What doesn't make sense to me is that the function called is beautiful.at_screen_connect, but beautiful doesn't have at_screen_connect() defined anywhere in it, so isn't THAT the nil value? Where is that function defined?

**Comment by lcpz** [comment] 2018-05-18 09:48
@trumbis That function is defined in `awesome-copycats` themes. This is an [example](https://github.com/lcpz/awesome-copycats/blob/master/themes/blackburn/theme.lua#L206).

If you're not using one of my themes, paste the full X error log. Note that you can also install latest Gio version following this [post](https://github.com/lcpz/lain/issues/387#issuecomment-368223707).

**Closed** 2022-03-24 19:48 UTC
