### ISSUE TITLE
Notification fonts in fs and weather widgets

### ISSUE THREAD

**Issue by cyberl33t** [lcpz/lain#456] opened 2020-05-30 09:20 UTC
The notification popup on fs and weather widgets both ignore the font specified in notification_preset, stubbornly using the theme.font instead. The colors are changeable, though. Strangely, the same font works fine with calendar widget.
-- awesome -v:
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
-- lua -v:
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
-- lain-git on Arch Linux

**Comment by lcpz** [comment] 2020-05-30 18:44
I can't replicate.

Please paste me your full configs, or a minimum replicable example.

**Comment by cyberl33t** [comment] 2020-06-01 10:09
<facepalm>Aw, this is embarrassing... In both the fs and weather configs, a comma was accidentally replaced by a full stop. I triple-checked everyting else... except that</facepalm>. The font issue was thus my fault.
But there's another problem with the fs notification: the colums are all over the place, as you can see in 
https://pasteboard.co/Jb3qQJE.png

**Comment by lcpz** [comment] 2020-06-02 00:07
Possibly related to https://github.com/lcpz/lain/pull/455.

@nevillelyh Could you give it a look? I will try to catch up ASAP.

**Comment by nevillelyh** [comment] 2020-06-02 00:57
I can't reproduce the font preset issue with latest master. The alignment issue should be fixed by #455. @cyberl33t what's the git hash are you using?

**Comment by cyberl33t** [comment] 2020-06-02 10:28
I am using the Arch AUR lain-git package, which uses git snapshots instead of straight-out git. The snapshot was unfortunately missing the latest fs-fix commit. So I copied fs.lua from git over the one installed by package, and now the fs notification is working fine, thank you very much :)

But, as I understood @lcpz  is also a maintainer of the mentioned Arch package, right? So, could you please update the package to include the new fs.lua?

**Comment by lcpz** [comment] 2020-06-02 16:53
> So, could you please update the package to include the new fs.lua?

Done, sorry for the inconvenience.

**Closed by lcpz** 2020-06-02 16:53 UTC
